name: 'Push'

on:
  push:
    branches:
      - main
      - canary
      - develop
      - ci/**
      - feature/**
      - fix/**
      - refactor/**
      - release/**

concurrency:
  group: push-${{ github.ref }}-1
  cancel-in-progress: true

env:
  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  pull:
    name: 'CI'
    if: (github.ref == 'refs/heads/main') &&
      !contains(github.event.head_commit.message, '[skip ci]')
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: 'Checkout'
        id: pull-checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
          token: ${{ secrets.YGOR_LUIZ }}

      - name: 'Init'
        id: push-init
        uses: YgorLuiz/monorepo/.github/actions/init@main

      - name: 'Install'
        id: push-install
        uses: YgorLuiz/monorepo/.github/actions/install@main

      - name: 'Turbo Cache'
        id: push-cache-turbo
        uses: YgorLuiz/monorepo/.github/actions/cache-turbo@main
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: 'Lint'
        id: push-lint
        uses: YgorLuiz/monorepo/.github/actions/lint@main
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      # https://docs.github.com/en/actions/learn-github-actions/expressions
      - name: 'Commit Message'
        id: push-commit-message
        run: |
          echo "::set-output name=message::$(git log --no-merges -1 --oneline)"

      - name: 'Build'
        id: push-build
        uses: YgorLuiz/monorepo/.github/actions/build@main
        with:
          BUILD_COMMAND: 'build'
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: 'Build ALL'
        id: push-build-all
        if: ${{ contains(steps.push-commit-message.outputs.message, '[b]') }}
        uses: YgorLuiz/monorepo/.github/actions/build@main
        with:
          BUILD_COMMAND: 'build:all'
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: 'ci(changesets): version packages'
          setupGitUser: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Create @dev release
      #   if: steps.changesets.outputs.published != 'true'
      #   run: |
      #     git checkout main
      #     pnpm version:dev
      #     pnpm release:dev
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      # - name: Update changelog
      #   if: steps.changesets.outputs.published == 'true'
      #   run: |
      #     pnpm changelog:latest
      #     pnpm changelog:format
      #     pnpm changelog:commit

      - name: 'Deploy (Production)'
        id: push-deploy
        if: github.ref == 'refs/heads/main'
        uses: YgorLuiz/monorepo/.github/actions/deploy@main
        with:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PRODUCTION: true
